### ISSUE TITLE
新站点提交

### ISSUE THREAD

**Issue by alect001** [TulvL/IPv6.stream#5]
**服务商**  
购买服务器所属 ISP 的名称  
hetzner  
**地区**  
服务器所在地区  
德国巴伐利亚州纽伦堡  
**IPv6 地址**  
2a01:4f8:172:1d6e::8  
**备注**  
无  

**提供者**
和邪社

**测速地址**（二选一）  
https://hetzner.69cdn.com
双栈支持
如有必要可以删除v4的解析

**Comment by TulvL** [comment]
已收录
