### ISSUE TITLE
新站点提交

### ISSUE THREAD

**Issue by ddnspod** [TulvL/IPv6.stream#6]
**服务商**  
中国移动
  
**地区**  
中国 浙江 金华
  
**IPv6 地址**  
2409:8a28:6a00::/36 
  
**备注**  
IPv6 Only千兆对等家宽，NAS自建

**提供者**
ip6 plus

**测速地址**（二选一）  
1. 提供者自己的域名  
[speedtest.ip6.plus:10443](https://speedtest.ip6.plus:10443/)

2. 本站提供域名  
提供格式：A.B.ipv6.stream  
A 表示服务商和地区，格式参照已有节点域名，可以带有"."
B 表示提供者
被指向的页面不应有广告等无关测速的内容    
可以含有所在服务器的购买链接，如为 aff 需明示  
请尽可能在解析完成后7天内配置完成 HTTPS   

**提示**
上述链接所指向的页面均不应含有任何可能违反中国、美国、欧盟法律的内容

**Comment by TulvL** [comment]
你好，访问后显示“您要找的页面未找到”

**Comment by shenfuba** [comment]
https://www.cesu.net/
